---
services:
  kore.layout.element.vue_component.backend:
    class: Kore\Layout\Element\Backend\VueComponent

  kore.layout.element.html.vue_component.frontend:
    class: Kore\Layout\Element\Frontend\Html\VueComponent
    calls:
     - ['setAssetResolver', ['@kore.layout.asset.resolver']]

  kore.layout.element.html.vue_component:
    class: Kore\Layout\Element\Element
    public: true
    arguments:
      - '@kore.layout.element.vue_component.backend'
      - '@kore.layout.element.html.vue_component.frontend'
    tags:
      - { name: 'kore.layout.html.element', 'alias': 'vue_component'}
