index:
    path: /
    controller: App\Controller\HomeController::index
contacts:
    path: /contacts
    controller: App\Controller\ContactsController::index
user:
    path: /user
    controller: App\Controller\UserController::index
user_login:
    path: /user/login
    controller: App\Controller\UserController::login