---
default: # Default Handler - Will be applied to all pages
  document: # Root Element
    _type: template
    _template: default.pug
    head:
      _type: document_head
      _title: The Demo Page
    footer:
      _type: template
      _template: footer.phtml
      copyright:
        _type: template
        _template: copyright.twig
